Added train_with_arcface with the new training implementation
mariacsalazar/face_verification_bias_model pull request #10
Opened 2024-11-18 12:43 UTC by hareemraza

Modified the arcface_loss using Maria's modified pipeline, new iresnet implementation and Alexander's feedback. There is a very slight improvement in the way arcface_loss behaves but the accuracy shows no improvement so far. 

Open to any feedback.

2024-11-19 16:51 UTC, Matematikoi commented on src/train_with_arcface.py
This shouldn't be a new file. Add a new parameter to the script that allows us to change between losses as we change between size of epochs.

2024-11-19 16:53 UTC, Matematikoi commented on src/train_with_arcface.py
> +        super(ArcFace, self).__init__()
are these parameters something we should worry about in the future? or we are probably never changing them?

2024-11-19 16:56 UTC, Matematikoi requested changes
Its hard to review since it is a completely new file. We should probably just have a parameter to switch between losses since everything else is the same and we are not planning on maintaining two codes at the same time

2024-11-19 19:44 UTC, hareemraza commented on src/train_with_arcface.py
Done!
Now we have a single train file with an option to choose between losses

2024-11-19 19:45 UTC, hareemraza commented on src/train_with_arcface.py
> +        super(ArcFace, self).__init__()
We dont need to change them. Experimented with alot of parameters. These are the defaults ones used by insightface itself (also recommended by Alexander)

2024-11-19 20:08 UTC, Matematikoi reviewed
just a small issue with the resnet architecture

2024-11-19 20:08 UTC, Matematikoi commented on src/train.py
> +        self.base_model.fc = nn.Identity()
you are not using this layer

2024-11-20 14:44 UTC, afm215 commented on src/train.py
> +        # optimizer.step()
This should be uncommented, if not weights are never updated

2024-11-20 14:49 UTC, afm215 commented on src/train.py
> +            scheduler.step()
This should be put into the epoch loop over batches

2024-11-20 16:02 UTC, hareemraza commented on src/train.py
> +        # optimizer.step()
Just cross-checked. This was commented by mistake (while commenting gradient clipping). Fixed in the latest commit.

2024-12-04 11:28 UTC, merged